name: Test

on:
  push:
    branches: ['**']

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT_MINUTES) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run format-check

      - name: Run linter
        run: npm run lint

      - name: Run typecheck
        run: npm run type-check

      - name: Run unit tests
        run: npm run test

  check-types:
    name: Check generated types are up to date
    runs-on: ubuntu-latest
    timeout-minutes: ${{ fromJSON(vars.DEFAULT_JOB_TIMEOUT_MINUTES) }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate types
        run: npm run generate-types

      - name: Commit updated types or fail on main
        run: |
          git add -- $(find . -name "*.d.ts" -not -path "./node_modules/*")
          if git diff --cached --quiet; then
            echo "Types are up to date"
            git restore --staged .
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Types are out of date on main!"
            git diff --cached
            exit 1
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "chore: regenerate types"
            git push
          fi
